
const T={
zh:{brandSub:"全球数字化解决方案平台",navHome:"首页",navCenters:"业务中心",navSolutions:"解决方案",navCases:"案例",navContact:"联系",networkSub:"连接全球业务与数字能力",heroTitle:"让 AI 帮助企业完成数字化升级",heroSub:"从网站、人工智能到自动化运营，用一个平台匹配真正适合你的解决方案。",searchPlaceholder:"输入你想解决的问题，例如：我想卖数字产品",searchBtn:"AI 搜索",m1:"业务中心",m2:"核心服务",m3:"语言支持",centersTitle:"四大业务中心",centersSub:"每个中心都是独立的搜索与解决方案入口。",webTitle:"网站建设",webSub:"企业官网、跨境商城、AI 网站、多语言站点。",aiTitle:"人工智能",aiSub:"AI 客服、写作、图片、办公与智能体。",autoTitle:"自动化运营",autoSub:"Telegram、WhatsApp、邮件与工作流。",digitalTitle:"数字化方案",digitalSub:"数字产品、课程、SaaS、支付与自动交付。",enter:"进入中心 →",solutionsTitle:"六大核心解决方案",solutionsSub:"从品牌展示到获客成交，覆盖完整数字链路。",sectionSearch:"搜索解决方案",casesTitle:"数字化增长场景",casesSub:"按不同目标组合网站、AI 与自动化能力。",case1Title:"企业品牌升级",case1Sub:"多语言官网、品牌视觉、线索收集和移动端优化。",case2Title:"跨境电商启动",case2Sub:"商品展示、社媒引流、客户咨询与自动化运营。",case3Title:"数字产品销售",case3Sub:"独立站、支付系统、数字交付和售后支持。",stat1:"在线入口",stat2:"语言覆盖",stat3:"统一平台",matchTitle:"描述目标，立即获得组合方案",matchQuestion:"你现在最想解决什么？",matchPlaceholder:"例如：我只用手机做跨境电商",generate:"生成方案",resultEmpty:"输入需求，这里会显示匹配结果。",contactTitle:"准备开始你的数字化项目？",contactSub:"告诉我们你的目标，GlobalYouXuan 将为你匹配合适的执行方案。",contactBtn:"立即联系",footerSub:"全球数字化解决方案平台"},
en:{brandSub:"Global Digital Solutions",navHome:"Home",navCenters:"Centers",navSolutions:"Solutions",navCases:"Cases",navContact:"Contact",networkSub:"Connecting global business with digital capability",heroTitle:"Let AI accelerate your digital transformation",heroSub:"Match website, AI and automation solutions in one platform.",searchPlaceholder:"Describe the problem you want to solve",searchBtn:"AI Search",m1:"Centers",m2:"Services",m3:"Languages",centersTitle:"Four Business Centers",centersSub:"Each center is an independent search and solution entry.",webTitle:"Website Development",webSub:"Corporate websites, ecommerce, AI websites and multilingual sites.",aiTitle:"Artificial Intelligence",aiSub:"AI support, writing, images, office tools and agents.",autoTitle:"Automation",autoSub:"Telegram, WhatsApp, email and workflows.",digitalTitle:"Digital Solutions",digitalSub:"Digital products, courses, SaaS, payments and delivery.",enter:"Enter Center →",solutionsTitle:"Six Core Solutions",solutionsSub:"A complete digital path from brand to conversion.",sectionSearch:"Search solutions",casesTitle:"Digital Growth Scenarios",casesSub:"Combine websites, AI and automation for different goals.",case1Title:"Brand Upgrade",case1Sub:"Multilingual website, visual identity, lead capture and mobile optimization.",case2Title:"Cross-border Ecommerce",case2Sub:"Product display, social traffic, customer support and automation.",case3Title:"Digital Product Sales",case3Sub:"Independent site, payments, digital delivery and support.",stat1:"Online Access",stat2:"Language Reach",stat3:"Unified Platform",matchTitle:"Describe your goal and get a combined plan",matchQuestion:"What do you want to solve now?",matchPlaceholder:"Example: run cross-border ecommerce on mobile",generate:"Generate Plan",resultEmpty:"Enter your need to see matched results.",contactTitle:"Ready to start your digital project?",contactSub:"Tell us your goal and GlobalYouXuan will match the right execution plan.",contactBtn:"Contact Now",footerSub:"Global Digital Solutions Platform"},
km:{brandSub:"វេទិកាដំណោះស្រាយឌីជីថល",navHome:"ទំព័រដើម",navCenters:"មជ្ឈមណ្ឌល",navSolutions:"ដំណោះស្រាយ",navCases:"ករណី",navContact:"ទំនាក់ទំនង",networkSub:"ភ្ជាប់អាជីវកម្មសកល និងសមត្ថភាពឌីជីថល",heroTitle:"ប្រើ AI ដើម្បីពន្លឿនការផ្លាស់ប្តូរឌីជីថល",heroSub:"ផ្គូផ្គងគេហទំព័រ AI និងស្វ័យប្រវត្តិកម្មក្នុងវេទិកាតែមួយ។",searchPlaceholder:"បញ្ចូលបញ្ហាដែលអ្នកចង់ដោះស្រាយ",searchBtn:"ស្វែងរក AI",m1:"មជ្ឈមណ្ឌល",m2:"សេវា",m3:"ភាសា",centersTitle:"មជ្ឈមណ្ឌលអាជីវកម្ម ៤",centersSub:"មជ្ឈមណ្ឌលនីមួយៗមានការស្វែងរក និងដំណោះស្រាយផ្ទាល់ខ្លួន។",webTitle:"ការសាងសង់គេហទំព័រ",webSub:"គេហទំព័រក្រុមហ៊ុន អ៊ីកូម៉ឺស AI និងពហុភាសា។",aiTitle:"បញ្ញាសិប្បនិម្មិត",aiSub:"AI សេវាអតិថិជន សរសេរ រូបភាព ការិយាល័យ និង Agent។",autoTitle:"ស្វ័យប្រវត្តិកម្ម",autoSub:"Telegram WhatsApp Email និង workflow។",digitalTitle:"ដំណោះស្រាយឌីជីថល",digitalSub:"ផលិតផលឌីជីថល វគ្គសិក្សា SaaS ការទូទាត់ និងការបញ្ជូន។",enter:"ចូលមជ្ឈមណ្ឌល →",solutionsTitle:"ដំណោះស្រាយស្នូល ៦",solutionsSub:"គ្របដណ្តប់ពីម៉ាកដល់ការបម្លែង។",sectionSearch:"ស្វែងរកដំណោះស្រាយ",casesTitle:"សេណារីយ៉ូកំណើនឌីជីថល",casesSub:"រួមបញ្ចូលគេហទំព័រ AI និងស្វ័យប្រវត្តិកម្ម។",case1Title:"ការលើកកម្ពស់ម៉ាក",case1Sub:"គេហទំព័រពហុភាសា ម៉ាក ការប្រមូល lead និង mobile។",case2Title:"អ៊ីកូម៉ឺសឆ្លងដែន",case2Sub:"បង្ហាញផលិតផល social traffic customer support និង automation។",case3Title:"លក់ផលិតផលឌីជីថល",case3Sub:"គេហទំព័រ ការទូទាត់ ការបញ្ជូនឌីជីថល និង support។",stat1:"ចូលប្រើអនឡាញ",stat2:"ភាសា",stat3:"វេទិកាតែមួយ",matchTitle:"ពិពណ៌នាគោលដៅ និងទទួលផែនការ",matchQuestion:"តើអ្នកចង់ដោះស្រាយអ្វី?",matchPlaceholder:"ឧទាហរណ៍៖ អ៊ីកូម៉ឺសតាមទូរស័ព្ទ",generate:"បង្កើតផែនការ",resultEmpty:"បញ្ចូលតម្រូវការដើម្បីមើលលទ្ធផល។",contactTitle:"ត្រៀមចាប់ផ្តើមគម្រោងឌីជីថល?",contactSub:"ប្រាប់គោលដៅ ហើយ GlobalYouXuan នឹងផ្គូផ្គងផែនការ។",contactBtn:"ទាក់ទងឥឡូវ",footerSub:"វេទិកាដំណោះស្រាយឌីជីថលសកល"}
};

const services=[
["企业官网","品牌展示、业务介绍、联系转化。"],["AI 网站","搜索驱动、智能推荐、内容辅助。"],["跨境商城","多语言展示、商品与支付链路。"],["自动化运营","消息、客服、线索和流程自动化。"],["AI 办公","写作、整理、客服与知识库。"],["品牌营销","内容、社媒、短视频与增长方案。"]
];
const plans=[
{keys:["数字","卖","课程"],title:"数字产品销售方案",desc:"独立站 + 在线支付 + 自动交付 + Telegram 客服。",tags:["独立站","支付系统","自动交付","客户支持"]},
{keys:["网站","官网","企业"],title:"企业官网建设方案",desc:"企业官网 + 多语言 + 手机适配 + 联系转化。",tags:["企业官网","多语言","移动端","咨询入口"]},
{keys:["客服","自动回复","telegram","whatsapp"],title:"AI 客服自动化方案",desc:"AI 客服 + Telegram/WhatsApp + FAQ 知识库 + 线索记录。",tags:["AI 客服","消息自动化","知识库","线索管理"]},
{keys:["跨境","电商","商城"],title:"跨境电商启动方案",desc:"跨境商城 + 多语言 + 商品展示 + 社媒引流 + 客服自动化。",tags:["跨境商城","多语言","社媒引流","自动客服"]}
];
function renderServices(){document.getElementById("solutionGrid").innerHTML=services.map((s,i)=>`<article class="solution-card"><span>SOLUTION 0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join("")}
function setLang(l){const d=T[l]||T.zh;document.querySelectorAll("[data-i18n]").forEach(e=>{if(d[e.dataset.i18n])e.textContent=d[e.dataset.i18n]});document.querySelectorAll("[data-i18n-placeholder]").forEach(e=>{if(d[e.dataset.i18nPlaceholder])e.placeholder=d[e.dataset.i18nPlaceholder]});document.querySelectorAll(".langs button").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));localStorage.setItem("gyxLang",l)}
function showPlan(q){q=(q||"").trim();const p=plans.find(x=>x.keys.some(k=>q.toLowerCase().includes(k)))||{title:"综合数字化解决方案",desc:"先进行需求诊断，再组合网站、AI 与自动化能力。",tags:["需求诊断","网站建设","人工智能","自动化运营"]};document.getElementById("result").innerHTML=`<div class="result-card"><span class="eyebrow">AI MATCHED SOLUTION</span><h3>${p.title}</h3><p>${p.desc}</p><div class="result-tags">${p.tags.map(t=>`<span>${t}</span>`).join("")}</div></div>`;document.querySelector(".ai-match").scrollIntoView({behavior:"smooth"})}
document.addEventListener("DOMContentLoaded",()=>{renderServices();setLang(localStorage.getItem("gyxLang")||"zh");document.querySelectorAll(".langs button").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>showPlan(b.dataset.q));[["mainSearch","mainSearchInput"],["solutionSearch","solutionInput"],["matchSearch","matchInput"]].forEach(([f,i])=>document.getElementById(f).onsubmit=e=>{e.preventDefault();showPlan(document.getElementById(i).value)})});
